// <auto-generated />
using System;
using GestionCabanas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionCabanas.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260904055012_AgregarUltimaModificacionExcelVista")]
    partial class AgregarUltimaModificacionExcelVista
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("GestionCabanas.Models.AdminUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("AdminUsuarios");
                });

            modelBuilder.Entity("GestionCabanas.Models.Cabana", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activa")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacidad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PrecioPorNoche")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cabanas");
                });

            modelBuilder.Entity("GestionCabanas.Models.FotoCabana", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CabanaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Orden")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CabanaId");

                    b.ToTable("Fotos");
                });

            modelBuilder.Entity("GestionCabanas.Models.InformacionSitio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ComoLlegar")
                        .HasMaxLength(3000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Comodidades")
                        .HasMaxLength(3000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Direccion")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("InformacionAdicional")
                        .HasMaxLength(3000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("InformacionSitio");
                });

            modelBuilder.Entity("GestionCabanas.Models.OneDriveConexion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CuentaEmail")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaConexion")
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshTokenCifrado")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UltimaModificacionExcelVista")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UltimaSincronizacion")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("OneDriveConexiones");
                });

            modelBuilder.Entity("GestionCabanas.Models.PreguntaFrecuente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Orden")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Pregunta")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Respuesta")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PreguntasFrecuentes");
                });

            modelBuilder.Entity("GestionCabanas.Models.Promocion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Etiqueta")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("Lado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Promociones");
                });

            modelBuilder.Entity("GestionCabanas.Models.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CabanaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadPersonas")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExcelUbicacion")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaDesde")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaHasta")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreHuesped")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CabanaId");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("GestionCabanas.Models.TarifaDia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Bloqueada")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CabanaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Precio")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CabanaId", "Fecha")
                        .IsUnique();

                    b.ToTable("TarifasDias");
                });

            modelBuilder.Entity("GestionCabanas.Models.FotoCabana", b =>
                {
                    b.HasOne("GestionCabanas.Models.Cabana", "Cabana")
                        .WithMany("Fotos")
                        .HasForeignKey("CabanaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cabana");
                });

            modelBuilder.Entity("GestionCabanas.Models.Reserva", b =>
                {
                    b.HasOne("GestionCabanas.Models.Cabana", "Cabana")
                        .WithMany("Reservas")
                        .HasForeignKey("CabanaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cabana");
                });

            modelBuilder.Entity("GestionCabanas.Models.TarifaDia", b =>
                {
                    b.HasOne("GestionCabanas.Models.Cabana", "Cabana")
                        .WithMany("TarifasDias")
                        .HasForeignKey("CabanaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cabana");
                });

            modelBuilder.Entity("GestionCabanas.Models.Cabana", b =>
                {
                    b.Navigation("Fotos");

                    b.Navigation("Reservas");

                    b.Navigation("TarifasDias");
                });
#pragma warning restore 612, 618
        }
    }
}
